language: python
python:
  - "2.7"
  - "3.6"

before_install:
  - cd $TRAVIS_BUILD_DIR/..
  - git clone https://github.com/cpgr/pyexodiff.git
  - cd $TRAVIS_BUILD_DIR

install:
  # Install required python modules
  - pip install pandas
  - pip install pytest
  - pip install pyYAML
  - pip install netCDF4

script: python -m pytest --exodiff ../pyexodiff/pyexodiff.py run_tests.py
